<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_diffbot">

<!-- Here we define the model parameters -->
    <!-- Geometry -->
    <xacro:property name="base_link_width" value="0.44"/>
    <xacro:property name="base_link_length" value="0.48"/>
    <xacro:property name="base_link_height" value="0.05"/>

    <xacro:property name="wheel_link_length" value="0.03"/>
    <xacro:property name="wheel_link_radius" value="0.05"/>

    <xacro:property name="caster_link_radius" value="0.025"/>

    <!-- Pi Constant -->
    <xacro:property name="PI" value="3.14159265"/>

    <!-- Material density -->
    <!-- <xacro:property name="body_density" value="2710.0"/>
    <xacro:property name="wheel_density" value="2710.0"/>
    <xacro:property name="caster_density" value="2710.0"/> -->

    <!-- Mass -->
    <!-- <xacro:property name="base_link_mass" value="${body_density * base_link_width * base_link_length * base_link_height}"/>
    <xacro:property name="wheel_link_mass" value="${wheel_density * PI * wheel_link_radius * wheel_link_radius * wheel_link_length}"/>
    <xacro:property name="caster_link_mass" value="${caster_density * (4 / 3) * PI * caster_link_radius * caster_link_radius * caster_link_radius}"/> -->
    <xacro:property name="base_link_mass" value="10.0"/>
    <xacro:property name="wheel_link_mass" value="0.3"/>
    <xacro:property name="caster_link_mass" value="0.3"/>
    
<!-- Here we define the model -->
    <!-- DUMMY_LINK is used for Gazebo => Gazebo will complain if missing -->
    <!-- FOR REAL ROBOT, WE DONT NEED "DUMMYLINK" -->
    <!-- <link name="dummy_link"/>

    <joint name="base_joint" type="fixed">
        <parent link="dummy_link"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.01" rpy="0 0 0"/>
    </joint> -->


    <!-- Define base_footprint link -->
    <link name="base_footprint">
        <!-- Define visual for base_footprint (optional) -->
        <visual>
            <geometry>
                <!-- You can use any geometry you prefer, simply use a small sphere for visualization -->
                <sphere radius="0.01"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <!-- Match the visual geometry for collision purposes -->
                <sphere radius="0.01"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
    </link>

    <!-- Define a fixed joint connecting base_footprint to base_link -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>


    <!-- Define base_link -->
    <!--Actual body/chassis of the robot-->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_link_width} ${base_link_length} ${base_link_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="green"/>
        </visual>

        <!-- This is the main factors to simulate the robot's collision (va chamj) -->
        <collision>
            <geometry>
                <box size="${base_link_width} ${base_link_length} ${base_link_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        
        <inertial>
            <!-- mass in kg -->
            <mass value="${base_link_mass}"/> 
            <origin xyz="0.0 0.0 0.0"/>
            <!-- Moment of inertia tensor (Momen quans tinhs)-->
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>

    <!-- <gazebo reference="base_link">
        <turnGravityOff>false</turnGravityOff>
    </gazebo> -->

    <!-- Define left_wheel_joint -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0.0 0.22 -0.03" rpy="-1.57 0.0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>   
    </joint>

    <!-- Define left_wheel_link -->
    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0 0.0 0.0"/>
            <material name="yellow"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0 0.0 0.0"/>
        </collision>
        
        <inertial>
            <mass value="${wheel_link_mass}"/>
            <origin xyz="0.0 0.0 0.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>

    <!-- Define right_wheel_joint -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0.0 -0.22 -0.03" rpy="1.57 0.0 0.0"/>
        <axis xyz="0.0 0.0 -1.0"/>   
    </joint>

    <!-- Define right_wheel_link -->
    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0 0.0 0.0"/>
            <material name="yellow"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_link_radius}" length="${wheel_link_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0 0.0 0.0"/>
        </collision>
        
        <inertial>
            <mass value="${wheel_link_mass}"/>
            <origin xyz="0.0 0.0 0.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>

    <!-- Define caster_joint_1 -->
    <joint name="caster_joint_1" type="fixed">
        <parent link="base_link"/>
        <child link="caster_link_1"/>
        <origin xyz="0.15 0.0 -0.03"/>        
    </joint>

    <!-- Define caster_link_1 -->
    <link name="caster_link_1">
        <visual>
            <geometry>
                <sphere radius="${caster_link_radius}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0"/>
            <material name="yellow"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${caster_link_radius}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0"/>
        </collision>

        <inertial>
            <mass value="${caster_link_mass}"/>
            <origin xyz="0.0 0.0 0.0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
        </inertial>
    </link>

    <!-- Define caster_joint_2 -->
    <joint name="caster_joint_2" type="fixed">
        <parent link="base_link"/>
        <child link="caster_link_2"/>
        <origin xyz="-0.15 0.0 -0.03"/>        
    </joint>

    <!-- Define caster_link_2 -->
    <link name="caster_link_2">
        <visual>
            <geometry>
                <sphere radius="${caster_link_radius}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0"/>
            <material name="yellow"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${caster_link_radius}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0"/>
        </collision>

        <inertial>
            <mass value="${caster_link_mass}"/>
            <origin xyz="0.0 0.0 0.0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
        </inertial>
    </link>

    <!-- LIDAR -->
    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser"/>
        <axis xyz="0 1 0" />
        <origin xyz="0.08 0 0.07" rpy="0 0 0"/>
    </joint> 

    <link name="laser">
        <visual>
            <geometry>
                <mesh filename="package://robot_model/meshes/Hieuneee.dae"/>
            </geometry>
        </visual>

        <collision>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>

        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>

<!-- USE FOR CONTROLLING ROBOT -->
    <!-- Transmission -->
    <transmission name="trans_left">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_wheel_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_left">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="trans_right">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_wheel_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_right">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

</robot>